import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';

const TOKENS_PATH = resolve(import.meta.dirname, '..', 'tokens', 'tokens.json');
const OUTPUT_PATH = resolve(import.meta.dirname, '..', 'src', 'styles', 'tokens.css');

interface TokenValue {
  value: string;
}

type TokenGroup = {
  [key: string]: TokenValue | TokenGroup;
};

function isTokenValue(obj: unknown): obj is TokenValue {
  return typeof obj === 'object' && obj !== null && 'value' in obj && typeof (obj as TokenValue).value === 'string';
}

/**
 * Flatten a nested token object into CSS custom property declarations.
 * e.g. { color: { brand: { blue: { "1": { value: "#4BB1FA" } } } } }
 * → "--color-brand-blue-1: #4BB1FA;"
 */
function flattenTokens(obj: TokenGroup, prefix: string = ''): string[] {
  const lines: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    if (key === '$schema') continue;

    const propName = prefix ? `${prefix}-${camelToKebab(key)}` : camelToKebab(key);

    if (isTokenValue(value)) {
      lines.push(`  --${propName}: ${value.value};`);
    } else if (typeof value === 'object' && value !== null) {
      lines.push(...flattenTokens(value as TokenGroup, propName));
    }
  }

  return lines;
}

function camelToKebab(str: string): string {
  // Handle special cases like "2xl", "h1Xl", "p1Bold", etc.
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase();
}

function generate(): void {
  const raw = readFileSync(TOKENS_PATH, 'utf-8');
  const tokens = JSON.parse(raw) as TokenGroup;

  const lines = flattenTokens(tokens);

  const css = `/* =============================================================
 * Portals Game UI — Design Tokens (AUTO-GENERATED)
 * Source: tokens/tokens.json
 * DO NOT EDIT THIS FILE — run "npm run tokens" to regenerate
 * ============================================================= */

:root {
${lines.join('\n')}
}
`;

  // Ensure output directory exists
  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, css, 'utf-8');

  console.log(`✓ Generated ${lines.length} CSS custom properties → src/styles/tokens.css`);
}

generate();
